### ISSUE TITLE
Infinite redirect

### ISSUE THREAD

**Issue by AlexHilson** [met-office-lab/jade-pangeo#3]
1. Start a session
2. Restart the hub using docker compose
3. Try to log back into your session

Expected -> can resume session
Actual -> too many redirects browser error. Admin panel says no workers are running. Worker containers are still running. 

1. Start a session
2. Use the admin panel to stop the session
3. Restart the hub using docker compose
4. Try to start a new session.

Expected + Actual -> Able to start new session

Hypothesis is that if the hub is restarted it loses track of running containers. When a user with a running session tries to log in the hub get stuck in a 'please start container' -> 'no, container is already running' -> 'please start container' loop.

**Comment by jacobtomlinson** [comment]
I think this has been resolved in the jupyterhub chart.
